url: https://pdns-shield.github.io
baseurl: /pdns-privacy-website/  # the subpath of your site, e.g. /blog

# Site settings
title: PDNS Privacy Shield
email: vitaly-kamluk+pdns-shield@users.noreply.github.com
description: "Passive DNS Privacy Shield Project - Open Source Passive DNS Data Anonymization Tool"
github_url: https://github.com/privacy-shield/pdns

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/pdns
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Singapore
  #- line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
